create or replace package QS_PARSE_METADATA as
	TYPE QS_COL_REC IS RECORD (
		COLUMN_NAME VARCHAR2(100),
		COLUMN_TYPE	VARCHAR2(50),
		COLUMN_DIRECTIVES VARCHAR2(100)
	);

	TYPE QS_COLS_TAB IS TABLE OF QS_COL_REC;

	TYPE QS_TABLE IS RECORD (
		TABLE_NAME VARCHAR2(100),
		TABLE_DIRECTIVES VARCHAR2(100),
		TABLE_COLS QS_COLS_TAB
	);

	--IDENTATION
	G_IDNT CHAR(2) := '  ';
	--QUICK SQL COLUMN TYPES
	G_T_NUM 	VARCHAR2(5) := 'num';
	G_T_INT 	VARCHAR2(5) := 'int';
	G_T_DATE 	VARCHAR2(5) := 'date';
	G_T_TS 		VARCHAR2(5) := 'ts';
	G_T_TS_TZ 	VARCHAR2(5) := 'tstz';
	G_T_VC 		VARCHAR2(5) := 'vc';
	G_T_CLOB 	VARCHAR2(5) := 'clob';
	G_T_BLOB 	VARCHAR2(5) := 'blob';
	G_T_FILE 	VARCHAR2(5) := 'file';

	--QUICK SQL TABLE DIRECTIVES
	G_D_COMPRESSED VARCHAR2(10) := ' /compress';

	--QUICK SQL 


	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';
	G_NUM VARCHAR2(10) := 'num';

end QS_PARSE_METADATA; //